### ISSUE TITLE
Reachable unwrap in sys_futex()

### ISSUE THREAD

**Issue by Marsman1996** [asterinas/asterinas#1179]
### Describe the bug
Similar to #1173, there is a reachable unwrap caused by value convertion in `sys_futex()` at kernel/aster-nix/src/syscall/futex.rs:22 when make a `futex` syscall with specific arguments.
https://github.com/asterinas/asterinas/blob/0291b5dc6bb142b9c6165c1cb29b7658eefdaa63/kernel/aster-nix/src/syscall/futex.rs#L22
### To Reproduce
1. Compile a program which calls `rt_sigprocmask` with specific arguments:
```C
#include <errno.h>
#include <linux/futex.h>
#include <stdint.h>
#include <stdio.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <unistd.h>

int main() {
  uint32_t *uaddr = (uint32_t *)0x100068a0;
  uint32_t *uaddr2 = (uint32_t *)0x10006580;
  int op = 0xc;
  int val = 0x7fffffff;
  struct timespec timeout = {.tv_sec = 0, .tv_nsec = 1};
  int64_t val3 = 0xc0570d106a01;

  int result = syscall(SYS_futex, uaddr, op, val, &timeout, uaddr2, val3);

  return 0;
}
```
2. Run the compiled program in Asterinas.

### Expected behavior
Asterinas reports panic and is terminated.

### Environment
- Official docker asterinas/asterinas:0.6.2
- 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
- Asterinas version: main 0291b5d

### Logs

```
~ # /root/futex 
panicked at /root/asterinas/kernel/aster-nix/src/syscall/futex.rs:22:78:
called `Result::unwrap()` on an `Err` value: Error { errno: EINVAL, msg: Some("Unknown futex op") }
Printing stack trace:
   1: fn 0xffffffff887cc190 - pc 0xffffffff887cc1a8 / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aa490;

   2: fn 0xffffffff887cbf70 - pc 0xffffffff887cc0e8 / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aa4a0;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aa620;

   4: fn 0xffffffff8895b050 - pc 0xffffffff8895b0d2 / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aa630;

   5: fn 0xffffffff88938380 - pc 0xffffffff889384ab / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aa6c0;

   6: fn 0xffffffff884636d0 - pc 0xffffffff884637ac / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aa7c0;

   7: fn 0xffffffff88394fa0 - pc 0xffffffff883bbff2 / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6aab40;

   8: fn 0xffffffff8811a680 - pc 0xffffffff8811a70e / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c03d0;

   9: fn 0xffffffff880539e0 - pc 0xffffffff8805455f / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c0570;

  10: fn 0xffffffff8815ff90 - pc 0xffffffff8815ff9e / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c0f90;

  11: fn 0xffffffff887a65b0 - pc 0xffffffff887a65c6 / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c0fb0;

  12: fn 0xffffffff88842e80 - pc 0xffffffff88842ee9 / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c0fd0;

  13: fn                0x0 - pc                0x0 / registers:

     rax               0x12; rdx 0xffffffff889e4728; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c1000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:107
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) a3wadqd69fx2whpv190t0ri68:?
(  4) ??:?
(  5) ??:?
(  6) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1102
(  7) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:215
(  8) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:323
(  9) /root/asterinas/kernel/aster-nix/src/thread/task.rs:69
( 10) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 11) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 12) /root/asterinas/ostd/src/task/task/mod.rs:310
make: *** [Makefile:153: run] Error 1
```

**Comment by Marsman1996** [comment]
And use `syscall(SYS_futex, (uint32_t *)0x53000, 0xa, -9, &timeout, (uint32_t *)0x10007580, 0x40404040);` Asterinas will panic in  line 57:
https://github.com/asterinas/asterinas/blob/0291b5dc6bb142b9c6165c1cb29b7658eefdaa63/kernel/aster-nix/src/syscall/futex.rs#L45-L62

```log
/root/futex.c 
panicked at /root/asterinas/kernel/aster-nix/src/syscall/futex.rs:57:61:
Invalid futex val: Error { errno: EINVAL, msg: Some("the futex val must not be negative") }
Printing stack trace:
   1: fn 0xffffffff887cc960 - pc 0xffffffff887cc978 / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f02a310;

   2: fn 0xffffffff887cc740 - pc 0xffffffff887cc8b8 / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f02a320;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f02a4a0;

   4: fn 0xffffffff8895b820 - pc 0xffffffff8895b8a2 / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f02a4b0;

   5: fn 0xffffffff88938b50 - pc 0xffffffff88938c7b / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f02a540;

   6: fn 0xffffffff883cb8a0 - pc 0xffffffff883cb928 / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f02a640;

   7: fn 0xffffffff884550e0 - pc 0xffffffff88455707 / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f02a6b0;

   8: fn 0xffffffff883ea380 - pc 0xffffffff884113d2 / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f02ab40;

   9: fn 0xffffffff883ea0a0 - pc 0xffffffff883ea12e / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f0403d0;

  10: fn 0xffffffff885a9320 - pc 0xffffffff885a9e9f / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f040570;

  11: fn 0xffffffff8816caf0 - pc 0xffffffff8816cafe / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f040f90;

  12: fn 0xffffffff887a6d80 - pc 0xffffffff887a6d96 / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f040fb0;

  13: fn 0xffffffff88843650 - pc 0xffffffff888436b9 / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f040fd0;

  14: fn                0x0 - pc                0x0 / registers:

     rax               0x12; rdx 0xffffffff889e5040; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f041000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:107
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) a3wadqd69fx2whpv190t0ri68:?
(  4) ??:?
(  5) ??:?
(  6) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1059
(  7) /root/asterinas/kernel/aster-nix/src/syscall/futex.rs:57
(  8) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:215
(  9) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:323
( 10) /root/asterinas/kernel/aster-nix/src/thread/task.rs:69
( 11) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 12) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 13) /root/asterinas/ostd/src/task/task/mod.rs:310
make: *** [Makefile:153: run] Error 1
```
