### ISSUE TITLE
Reachable assert in `sys_mprotect()` by invalid `addr`

### ISSUE THREAD

**Issue by Marsman1996** [asterinas/asterinas#1184]
### Describe the bug

There is a reachable assert caused by invalid `addr` value in `sys_mprotect()` at kernel/aster-nix/src/syscall/mprotect.rs:15 when make a `mprotect` syscall with specific arguments.
https://github.com/asterinas/asterinas/blob/0291b5dc6bb142b9c6165c1cb29b7658eefdaa63/kernel/aster-nix/src/syscall/mprotect.rs#L15

### To Reproduce
1. Compile a program which calls `mprotect` with specific arguments:
```C
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/mman.h>
#include <errno.h>

int main() {
  mprotect(0xffffffff, 0, 0x5);

  return EXIT_SUCCESS;
}
```
2. Run the compiled program in Asterinas.

### Expected behavior
Asterinas reports panic and is terminated.

### Environment
- Official docker asterinas/asterinas:0.6.2
- 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
- Asterinas version: main 0291b5dc

### Logs
```
~ # /root/mprotect.c 
panicked at /root/asterinas/kernel/aster-nix/src/syscall/mprotect.rs:15:5:
assertion failed: addr % PAGE_SIZE == 0
Printing stack trace:
   1: fn 0xffffffff887ccd10 - pc 0xffffffff887ccd28 / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2aa660;

   2: fn 0xffffffff887ccaf0 - pc 0xffffffff887ccc68 / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2aa670;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2aa7f0;

   4: fn 0xffffffff8895bbd0 - pc 0xffffffff8895bc52 / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2aa800;

   5: fn 0xffffffff8895bd70 - pc 0xffffffff8895bdb0 / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2aa890;

   6: fn 0xffffffff884e8350 - pc 0xffffffff884e862d / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2aa900;

   7: fn 0xffffffff88519340 - pc 0xffffffff8851e37b / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2aab40;

   8: fn 0xffffffff8815cab0 - pc 0xffffffff8815cb3e / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2c03d0;

   9: fn 0xffffffff88567100 - pc 0xffffffff88567c7f / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2c0570;

  10: fn 0xffffffff880c9ef0 - pc 0xffffffff880c9efe / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2c0f90;

  11: fn 0xffffffff887a7130 - pc 0xffffffff887a7146 / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2c0fb0;

  12: fn 0xffffffff88843a00 - pc 0xffffffff88843a69 / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2c0fd0;

  13: fn                0x0 - pc                0x0 / registers:

     rax               0x12; rdx 0xffffffff889e5488; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f2c1000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:107
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) 86161ztg45fpd9b1tjbn4gsl1:?
(  4) ??:?
(  5) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:220
(  6) ao06edr9di1q0vhz8iz1v26bt:?
(  7) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:166
(  8) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:323
(  9) /root/asterinas/kernel/aster-nix/src/thread/task.rs:69
( 10) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 11) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 12) /root/asterinas/ostd/src/task/task/mod.rs:310
make: *** [Makefile:153: run] Error 1
```

**Comment by StevenJiang1110** [comment]
This problem will be fixed by #1180
