### ISSUE TITLE
index out of bounds in `find_posix_timer()`

### ISSUE THREAD

**Issue by Marsman1996** [asterinas/asterinas#1189]
### Describe the bug
There is a index out of bounds bug in `find_posix_timer()` at kernel/aster-nix/src/process/process/timer_manager.rs:190 when make a `timer_settime` syscall with specific arguments.
https://github.com/asterinas/asterinas/blob/0291b5dc6bb142b9c6165c1cb29b7658eefdaa63/kernel/aster-nix/src/process/process/timer_manager.rs#L189-L191

1. Compile a program which calls `timer_settime` with specific arguments:
```C
#include <stdio.h>
#include <time.h>
#include <errno.h>
#include <string.h>
#include <sys/mman.h>

int main() {
    char* ptr1 = mmap(NULL, 4096, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    int result = timer_settime(206, 0x1, ptr1, ptr1+1);

    return 0;
}
```
2. Run the compiled program in Asterinas.

### Expected behavior
Asterinas reports panic and is terminated.

### Environment

- Official docker asterinas/asterinas:0.6.2
- 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
- Asterinas version: main 0291b5dc

### Logs
```
~ # /root/timer_set.c 
panicked at /root/asterinas/kernel/aster-nix/src/process/process/timer_manager.rs:190:33:
index out of bounds: the len is 0 but the index is 206
Printing stack trace:
   1: fn 0xffffffff887cced0 - pc 0xffffffff887ccee8 / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4aa330;

   2: fn 0xffffffff887cccb0 - pc 0xffffffff887cce28 / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4aa340;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4aa4c0;

   4: fn 0xffffffff8895bd90 - pc 0xffffffff8895be12 / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4aa4d0;

   5: fn 0xffffffff8895c0b0 - pc 0xffffffff8895c1c8 / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4aa560;

   6: fn 0xffffffff884a5a70 - pc 0xffffffff884a5ac4 / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4aa650;

   7: fn 0xffffffff884b8310 - pc 0xffffffff884b8389 / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4aa690;

   8: fn 0xffffffff88444ef0 - pc 0xffffffff88444f54 / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4aa700;

   9: fn 0xffffffff88090470 - pc 0xffffffff880908cb / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4aa750;

  10: fn 0xffffffff88136b80 - pc 0xffffffff8815f8fe / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4aab40;

  11: fn 0xffffffff88121f60 - pc 0xffffffff88121fee / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4c03d0;

  12: fn 0xffffffff88515020 - pc 0xffffffff88515b9f / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4c0570;

  13: fn 0xffffffff884522a0 - pc 0xffffffff884522ae / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4c0f90;

  14: fn 0xffffffff887a72f0 - pc 0xffffffff887a7306 / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4c0fb0;

  15: fn 0xffffffff88843bc0 - pc 0xffffffff88843c29 / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4c0fd0;

  16: fn                0x0 - pc                0x0 / registers:

     rax               0x12; rdx 0xffffffff889e5558; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f4c1000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:107
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) 86161ztg45fpd9b1tjbn4gsl1:?
(  4) ??:?
(  5) ??:?
(  6) ??:?
(  7) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:16
(  8) /root/asterinas/kernel/aster-nix/src/process/process/timer_manager.rs:190
(  9) /root/asterinas/kernel/aster-nix/src/syscall/timer_settime.rs:27
( 10) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:173
( 11) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:323
( 12) /root/asterinas/kernel/aster-nix/src/thread/task.rs:69
( 13) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 14) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 15) /root/asterinas/ostd/src/task/task/mod.rs:310
make: *** [Makefile:153: run] Error 1
```

**Comment by tatetian** [comment]
Cool. Thanks for reporting the bug!
