### ISSUE TITLE
Reachable unwrap panic in `align_up` caused by large `size`

### ISSUE THREAD

**Issue by Marsman1996** [asterinas/asterinas#1214]
### Describe the bug
There is a reachable unwrap panic in `align_up` at ostd/libs/align_ext/src/lib.rs:74 when make a `munmap` syscall with large `size` (i.e., `0xffffffffffffffff`).

https://github.com/asterinas/asterinas/blob/562e64437584279783f244edba10b512beddc81d/ostd/libs/align_ext/src/lib.rs#L61

### To Reproduce
1. Compile a program which calls `munmap`:
```C
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <unistd.h>

int main() {
  void *addr = mmap(NULL, 4096, 0x3, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
  munmap(addr, 0xffffffffffffffff);

  return EXIT_SUCCESS;
}
```
2. Run the compiled program in Asterinas.

### Expected behavior
Asterinas reports panic and is terminated.

### Environment
- Official docker asterinas/asterinas:0.6.2
- 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
- Asterinas version: main 562e6443

### Logs

```
~ # /root/munmap.c 
panicked at /root/asterinas/ostd/libs/align_ext/src/lib.rs:74:1:
called `Option::unwrap()` on a `None` value
Printing stack trace:
   1: fn 0xffffffff88869620 - pc 0xffffffff88869638 / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6a98f0;

   2: fn 0xffffffff88869400 - pc 0xffffffff88869578 / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6a9900;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6a9a80;

   4: fn 0xffffffff889a8700 - pc 0xffffffff889a8782 / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6a9a90;

   5: fn 0xffffffff889a88a0 - pc 0xffffffff889a88e0 / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6a9b20;

   6: fn 0xffffffff88991e80 - pc 0xffffffff88991e95 / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6a9b90;

   7: fn 0xffffffff885c02d0 - pc 0xffffffff885c03c0 / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6a9ba0;

   8: fn 0xffffffff88515de0 - pc 0xffffffff88516038 / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6a9c10;

   9: fn 0xffffffff88573420 - pc 0xffffffff88578a42 / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6a9f30;

  10: fn 0xffffffff88563460 - pc 0xffffffff885634ee / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c03d0;

  11: fn 0xffffffff88445c30 - pc 0xffffffff884467af / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c0570;

  12: fn 0xffffffff88401f60 - pc 0xffffffff88401f6e / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c0f90;

  13: fn 0xffffffff887c07e0 - pc 0xffffffff887c07f6 / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c0fb0;

  14: fn 0xffffffff887a6250 - pc 0xffffffff887a62b9 / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c0fd0;

  15: fn                0x0 - pc                0x0 / registers:

     rax               0x12; rdx 0xffffffff88a38508; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e6c1000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:107
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) 0yfjuqijmdltwb3g9ceg2tyxs:?
(  4) ??:?
(  5) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:220
(  6) ??:?
(  7) dxo5803zce17no7m33fsuqpvr:?
(  8) /root/asterinas/kernel/aster-nix/src/syscall/munmap.rs:14
(  9) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:164
( 10) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:328
( 11) /root/asterinas/kernel/aster-nix/src/thread/task.rs:69
( 12) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 13) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 14) /root/asterinas/ostd/src/task/task/mod.rs:310
make: *** [Makefile:153: run] Error 1
```

**Comment by Marsman1996** [comment]
Fixed by 1241
