### ISSUE TITLE
Capacity overflow in `create_message_buffer()`

### ISSUE THREAD

**Issue by Marsman1996** [asterinas/asterinas#1324]
### Describe the bug
There is a capacity overflow in `handle_page_faults_around()` at kernel/src/net/socket/util/message_header.rs:65 when call `recvfrom` with large `size`.

https://github.com/asterinas/asterinas/blob/8bfbdf6642a9d04db3490792926d6a299d1e30be/kernel/src/net/socket/util/message_header.rs#L65

### To Reproduce
1. Compile a program which calls `recvfrom`: 
```C
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <arpa/inet.h>

int main() {
    int fd = socket(1, 0x5, 0);
    char ubuf[8];
    ssize_t size = -7;
    int flags = 0x0;
    struct sockaddr_in addr;
    socklen_t addr_len = 18;

    recvfrom(fd, ubuf, size, flags, (struct sockaddr *)&addr, &addr_len);

    return 0;
}
```
2. Run the compiled program in Asterinas.

### Expected behavior

Asterinas reports capacity overflow and is terminated.

### Environment
- Official docker asterinas/asterinas:0.8.1
- 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
- Asterinas version: main 8bfbdf6

### Logs
```
~ # /root/recvfrom.c
DEBUG: sockfd = 79, buf = 0x291d000, len = 18446744073709551609, flags = (empty), src_addr = 0x100215c0, addrlen_ptr = 0x12
panicked at /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:25:5:
capacity overflow
Printing stack trace:
   1: fn 0xffffffff887e4960 - pc 0xffffffff887e49ca / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a94a0;

   2: fn 0xffffffff887e4770 - pc 0xffffffff887e48c0 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a9500;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a9650;

   4: fn 0xffffffff889c1f90 - pc 0xffffffff889c2012 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a9660;

   5: fn 0xffffffff88987480 - pc 0xffffffff889874a9 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a96f0;

   6: fn 0xffffffff88988bb0 - pc 0xffffffff88988bee / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a9730;

   7: fn 0xffffffff8874c680 - pc 0xffffffff8874c6df / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a9770;

   8: fn 0xffffffff88741850 - pc 0xffffffff88741884 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a97d0;

   9: fn 0xffffffff887492e0 - pc 0xffffffff887492ff / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a9870;

  10: fn 0xffffffff882d2e60 - pc 0xffffffff882d2ec1 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a9890;

  11: fn 0xffffffff8835d530 - pc 0xffffffff8835d5f1 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a98d0;

  12: fn 0xffffffff88318df0 - pc 0xffffffff883193a5 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a9a90;

  13: fn 0xffffffff884376d0 - pc 0xffffffff88445a0f / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6a9f30;

  14: fn 0xffffffff880f6fe0 - pc 0xffffffff880f706e / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6c03d0;

  15: fn 0xffffffff883eb490 - pc 0xffffffff883ec00f / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6c0570;

  16: fn 0xffffffff883a3ac0 - pc 0xffffffff883a3ace / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6c0f90;

  17: fn 0xffffffff888573a0 - pc 0xffffffff888573b6 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6c0fb0;

  18: fn 0xffffffff88832150 - pc 0xffffffff888321b9 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6c0fd0;


     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883ab57; rbp                0x0; rsp 0xffff80000a6c1000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:113
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) 73ctk84we8vz1kw7hv2sr00er:?
(  4) ??:?
(  5) alloc.4436a8b0cd505e33-cgu.0:?
(  6) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:594
(  7) ??:?
(  8) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_elem.rs:52
(  9) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2737
( 10) /root/asterinas/kernel/src/net/socket/util/message_header.rs:65
( 11) /root/asterinas/kernel/src/net/socket/unix/stream/socket.rs:331
( 12) /root/asterinas/kernel/src/syscall/recvfrom.rs:29
( 13) /root/asterinas/kernel/src/syscall/mod.rs:220
( 14) /root/asterinas/kernel/src/syscall/mod.rs:328
( 15) /root/asterinas/kernel/src/thread/task.rs:69
( 16) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 17) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 18) /root/asterinas/ostd/src/task/mod.rs:175
make: *** [Makefile:174: run] Error 1
```

**Comment by Marsman1996** [comment]
This should be fixed by commit 985813c
