### ISSUE TITLE
Capacity overflow in `sys_getrandom()`

### ISSUE THREAD

**Issue by Marsman1996** [asterinas/asterinas#1338]
### Describe the bug
There is a capacity overflow in `sys_getrandom()` at kernel/src/syscall/getrandom.rs:14 when call syscall `getrandom` with large `count` (i.e., 0xffff_ffff_ffff_ffff).

https://github.com/asterinas/asterinas/blob/8b1c69987f422f53f6a9075cf374aaea9e52d870/kernel/src/syscall/getrandom.rs#L14

### To Reproduce
1. Compile a program which calls `getrandom`: 
```C
#define _GNU_SOURCE
#include <errno.h>
#include <linux/random.h>
#include <stdio.h>
#include <sys/syscall.h>
#include <unistd.h>

int main() {
  unsigned char buffer[16];
  size_t num_bytes = -1;

  syscall(SYS_getrandom, buffer, num_bytes, 0);
  perror("getrandom");

  return 0;
}
```
2. Run the compiled program in Asterinas.

### Expected behavior

Asterinas reports capacity overflow and is terminated.

### Environment
- Official docker asterinas/asterinas:0.8.1
- 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
- Asterinas version: main 6fcad6c

### Logs
```
~ # /root/getrandom.c
panicked at /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:25:5:
capacity overflow
Printing stack trace:
   1: fn 0xffffffff887e71e0 - pc 0xffffffff887e724a / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa297b0;

   2: fn 0xffffffff887e6ff0 - pc 0xffffffff887e7140 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa29810;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa29960;

   4: fn 0xffffffff889c4840 - pc 0xffffffff889c48c2 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa29970;

   5: fn 0xffffffff88989d30 - pc 0xffffffff88989d59 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa29a00;

   6: fn 0xffffffff8898b460 - pc 0xffffffff8898b49e / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa29a40;

   7: fn 0xffffffff8874ef00 - pc 0xffffffff8874ef5f / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa29a80;

   8: fn 0xffffffff887440d0 - pc 0xffffffff88744104 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa29ae0;

   9: fn 0xffffffff8874bb60 - pc 0xffffffff8874bb7f / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa29b80;

  10: fn 0xffffffff880cce50 - pc 0xffffffff880ccee5 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa29ba0;

  11: fn 0xffffffff8843b8b0 - pc 0xffffffff88471e17 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa29f30;

  12: fn 0xffffffff880fc950 - pc 0xffffffff880fc9de / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa403d0;

  13: fn 0xffffffff88530380 - pc 0xffffffff88530eff / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa40570;

  14: fn 0xffffffff88396fa0 - pc 0xffffffff88396fae / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa40f90;

  15: fn 0xffffffff88859c20 - pc 0xffffffff88859c36 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa40fb0;

  16: fn 0xffffffff888349d0 - pc 0xffffffff88834a39 / registers:

     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa40fd0;


     rax                0x1; rdx                0x8; rcx                0x0; rbx                0x0;
     rsi                0x1; rdi 0xffffffff8883d3d7; rbp                0x0; rsp 0xffff80000aa41000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:113
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) 73ctk84we8vz1kw7hv2sr00er:?
(  4) ??:?
(  5) alloc.4436a8b0cd505e33-cgu.0:?
(  6) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:594
(  7) ??:?
(  8) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_elem.rs:52
(  9) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2737
( 10) /root/asterinas/kernel/src/syscall/getrandom.rs:15
( 11) /root/asterinas/kernel/src/syscall/mod.rs:171
( 12) /root/asterinas/kernel/src/syscall/mod.rs:328
( 13) /root/asterinas/kernel/src/thread/task.rs:69
( 14) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 15) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 16) /root/asterinas/ostd/src/task/mod.rs:175
make: *** [Makefile:172: run] Error 1
```

**Comment by Marsman1996** [comment]
Fixed by #2482
