### ISSUE TITLE
Hang by heap allocation in rescue with log print.

### ISSUE THREAD

**Issue by junyang-zh** [asterinas/asterinas#1367]
### Describe the bug

```shell
make run LOG_LEVEL=debug
```

will certainly hang at 

```
[     0.061] DEBUG: receive packet: token = 1, len = 602
[     0.061] DEBUG: DHCP recv Ack from 10.0.2.2: Repr { message_type: Ack, transaction_id: 1630584515, secs: 0, client_hardware_address: Address([82, 84, 0, 18, 52, 86]), clien}
[DHCP] Local IP address: Ipv4(Cidr { address: Address([10, 0, 2, 15]), prefix_len: 24 })
[DHCP] Router IP address: Address([10, 0, 2, 2])
[kernel] unpacking the initramfs.cpio.gz to rootfs ...
```

It's because that the rescue function trys to allocate from the heap when messaging with `fmt`:

https://github.com/asterinas/asterinas/blob/a997d9f0b06159020e2392ef197ad23b307d0cbd/ostd/src/mm/heap_allocator/mod.rs#L89-L93

trace:

```
#0  core::sync::atomic::atomic_compare_exchange<u8> (dst=0xffffffff8849f000 <_ZN4ostd2mm14heap_allocator14HEAP_ALLOCATOR17h85e988230dd34b42E.llvm.4954328986150445012>, old=0, 
    new=1, success=core::sync::atomic::Ordering::Acquire, failure=core::sync::atomic::Ordering::Relaxed)
    at /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:3373
#1  core::sync::atomic::AtomicBool::compare_exchange (self=0xffffffff8849f000 <_ZN4ostd2mm14heap_allocator14HEAP_ALLOCATOR17h85e988230dd34b42E.llvm.4954328986150445012>, 
    current=false, new=true, success=core::sync::atomic::Ordering::Acquire, failure=core::sync::atomic::Ordering::Relaxed)
    at /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/sync/atomic.rs:811
#2  ostd::sync::spin::SpinLock<ostd::mm::heap_allocator::slab_allocator::Heap, ostd::sync::spin::LocalIrqDisabled>::try_acquire_lock<ostd::mm::heap_allocator::slab_allocator::H)
    at src/sync/spin.rs:157
#3  ostd::sync::spin::SpinLock<ostd::mm::heap_allocator::slab_allocator::Heap, ostd::sync::spin::LocalIrqDisabled>::acquire_lock<ostd::mm::heap_allocator::slab_allocator::Heap,1
#4  ostd::sync::spin::SpinLock<ostd::mm::heap_allocator::slab_allocator::Heap, ostd::sync::spin::LocalIrqDisabled>::lock<ostd::mm::heap_allocator::slab_allocator::Heap, ostd::s4
#5  ostd::mm::heap_allocator::{impl#1}::alloc (self=0xffffffff8849f000 <_ZN4ostd2mm14heap_allocator14HEAP_ALLOCATOR17h85e988230dd34b42E.llvm.4954328986150445012>, layout=...)
    at src/mm/heap_allocator/mod.rs:61
#6  0xffffffff8804ac7e in ostd::mm::heap_allocator::_::__rust_alloc (size=4, align=1) at /root/asterinas/ostd/src/mm/heap_allocator/mod.rs:21
#7  alloc::alloc::alloc (layout=...) at src/alloc.rs:100
#8  alloc::alloc::Global::alloc_impl (layout=..., zeroed=false, self=<optimized out>) at src/alloc.rs:183
#9  alloc::alloc::{impl#1}::allocate (layout=..., self=<optimized out>) at src/alloc.rs:243
#10 alloc::raw_vec::RawVec<u8, alloc::alloc::Global>::try_allocate_in<u8, alloc::alloc::Global> (capacity=4, init=alloc::raw_vec::AllocInit::Uninitialized, alloc=...)
    at src/raw_vec.rs:230
#11 alloc::raw_vec::RawVec<u8, alloc::alloc::Global>::with_capacity_in<u8, alloc::alloc::Global> (capacity=<optimized out>) at src/raw_vec.rs:158
#12 alloc::vec::Vec<u8, alloc::alloc::Global>::with_capacity_in<u8, alloc::alloc::Global> (capacity=<optimized out>) at src/vec/mod.rs:699
#13 alloc::vec::Vec<u8, alloc::alloc::Global>::with_capacity<u8> (capacity=<optimized out>) at src/vec/mod.rs:481
#14 alloc::string::String::with_capacity () at src/string.rs:492
#15 alloc::fmt::format::format_inner (args=...) at src/fmt.rs:632
#16 0xffffffff8829a25e in alloc::fmt::format::{closure#0} ()
    at /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/fmt.rs:639
#17 core::option::Option<&str>::map_or_else<&str, alloc::string::String, alloc::fmt::format::{closure_env#0}, fn(&str) -> alloc::string::String> (self=..., default=..., 
    f=<optimized out>) at /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1207
#18 alloc::fmt::format (args=...) at /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/fmt.rs:639
#19 ostd::logger::{impl#0}::log (self=<optimized out>, record=0xffffffff88047168 <boot_stack_bottom+258408>) at src/logger.rs:37
#20 0xffffffff8827fab6 in log::__private_api::log_impl (args=..., level=log::Level::Debug, kvs=...)
    at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-0.4.22/src/__private_api.rs:61
#21 log::__private_api::log<()> (args=<error reading variable: Cannot access memory at address 0x20>, target_module_path_and_loc=<optimized out>, 
    args=<error reading variable: Cannot access memory at address 0x20>, target_module_path_and_loc=<optimized out>)
    at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-0.4.22/src/__private_api.rs:72
#22 ostd::mm::heap_allocator::rescue (layout=0xffffffff88047158 <boot_stack_bottom+258392>, heap=<optimized out>)
    at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-0.4.22/src/macros.rs:49
#23 ostd::mm::heap_allocator::{impl#1}::alloc (self=<optimized out>, layout=...) at src/mm/heap_allocator/mod.rs:68
#24 0xffffffff8810d2f3 in ostd::mm::heap_allocator::_::__rust_alloc (size=16968, align=8) at /root/asterinas/ostd/src/mm/heap_allocator/mod.rs:21
#25 alloc::alloc::alloc (layout=...) at /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:100
#26 allocator_api2::stable::alloc::global::Global::alloc_impl (layout=..., zeroed=false, self=<optimized out>)
    at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/allocator-api2-0.2.18/src/stable/alloc/global.rs:35
#27 allocator_api2::stable::alloc::global::{impl#1}::allocate (layout=..., self=<optimized out>)
    at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/allocator-api2-0.2.18/src/stable/alloc/global.rs:100
#28 hashbrown::raw::alloc::inner::do_alloc<allocator_api2::stable::alloc::global::Global> (layout=..., alloc=<optimized out>)
    at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.5/src/raw/alloc.rs:36
#29 hashbrown::raw::RawTableInner::new_uninitialized<allocator_api2::stable::alloc::global::Global> (table_layout=..., buckets=64, 
    fallibility=hashbrown::raw::Fallibility::Infallible, alloc=<optimized out>)
    at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.5/src/raw/mod.rs:1750
#30 hashbrown::raw::RawTableInner::fallible_with_capacity<allocator_api2::stable::alloc::global::Global> (alloc=<optimized out>, table_layout=..., capacity=<optimized out>, 
    fallibility=hashbrown::raw::Fallibility::Infallible) at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.5/src/raw/mod.rs:1788
#31 0xffffffff8810da36 in hashbrown::raw::RawTableInner::prepare_resize<allocator_api2::stable::alloc::global::Global> (alloc=<optimized out>, table_layout=..., capacity=1, 
    fallibility=<optimized out>, self=<optimized out>) at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.5/src/raw/mod.rs:2864
#32 hashbrown::raw::RawTableInner::resize_inner<allocator_api2::stable::alloc::global::Global> (
    self=0xffffffff88495878 <_ZN4ostd2mm14heap_allocator10HEAP_SPACE17h6e58867144a029e7E.llvm.4954328986150445012+1009784>, alloc=<optimized out>, capacity=1, 
    fallibility=<optimized out>, layout=..., hasher=...) at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.5/src/raw/mod.rs:3060
#33 hashbrown::raw::RawTableInner::reserve_rehash_inner<allocator_api2::stable::alloc::global::Global> (
    self=0xffffffff88495878 <_ZN4ostd2mm14heap_allocator10HEAP_SPACE17h6e58867144a029e7E.llvm.4954328986150445012+1009784>, alloc=<optimized out>, additional=<optimized out>, 
    layout=..., drop=..., hasher=..., fallibility=<optimized out>) at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.5/src/raw/mod.rs:2950
#34 hashbrown::raw::RawTable<(aster_nix::fs::utils::FixedCStr<256>, usize), allocator_api2::stable::alloc::global::Global>::reserve_rehash<(aster_nix::fs::utils::FixedCStr<256> 
    additional=<optimized out>, hasher=..., fallibility=<optimized out>) at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.5/src/raw/mod.rs:1231
#35 0xffffffff881496da in hashbrown::raw::RawTable<(aster_nix::fs::utils::FixedCStr<256>, usize), allocator_api2::stable::alloc::global::Global>::reserve<(aster_nix::fs::utils: 
    additional=1, hasher=...) at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.5/src/raw/mod.rs:1179
#36 hashbrown::raw::RawTable<(aster_nix::fs::utils::FixedCStr<256>, usize), allocator_api2::stable::alloc::global::Global>::find_or_find_insert_slot<(aster_nix::fs::utils::Fixe(
    self=0xffffffff88495878 <_ZN4ostd2mm14heap_allocator10HEAP_SPACE17h6e58867144a029e7E.llvm.4954328986150445012+1009784>, hash=6312116285085084924, eq=..., hasher=...)
    at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.5/src/raw/mod.rs:1413
#37 hashbrown::map::HashMap<aster_nix::fs::utils::FixedCStr<256>, usize, core::hash::BuildHasherDefault<ahash::fallback_hash::AHasher>, allocator_api2::stable::alloc::global::G(
    self=0xffffffff88495878 <_ZN4ostd2mm14heap_allocator10HEAP_SPACE17h6e58867144a029e7E.llvm.4954328986150445012+1009784>, k=..., v=28)
    at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.14.5/src/map.rs:1754
#38 0xffffffff8814db7b in aster_nix::fs::ramfs::fs::DirEntry::append_entry (
    self=0xffffffff88495858 <_ZN4ostd2mm14heap_allocator10HEAP_SPACE17h6e58867144a029e7E.llvm.4954328986150445012+1009752>, name=..., inode=...) at src/fs/ramfs/fs.rs:376
#39 aster_nix::fs::ramfs::fs::{impl#8}::create (self=<optimized out>, name=..., type_=aster_nix::fs::utils::inode::InodeType::Dir, mode=...) at src/fs/ramfs/fs.rs:820
#40 0xffffffff880bb6f9 in aster_nix::fs::path::dentry::Dentry_::create (
    self=0xffffffff8849a810 <_ZN4ostd2mm14heap_allocator10HEAP_SPACE17h6e58867144a029e7E.llvm.4954328986150445012+1030160>, name=..., 
    type_=aster_nix::fs::utils::inode::InodeType::Dir, mode=...) at src/fs/path/dentry.rs:149
#41 0xffffffff880bd5f1 in aster_nix::fs::path::dentry::Dentry::new_fs_child (
    self=0xffffffff88464050 <_ZN4ostd2mm14heap_allocator10HEAP_SPACE17h6e58867144a029e7E.llvm.4954328986150445012+806992>, name=..., type_=0, mode=...)
    at src/fs/path/dentry.rs:452
#42 0xffffffff88115197 in aster_nix::fs::rootfs::init (initramfs_buf=...) at src/fs/rootfs.rs:62
#43 0xffffffff88189c86 in aster_nix::init () at src/lib.rs:105
#44 0xffffffff8818d31e in aster_nix::main () at src/lib.rs:87
#45 0xffffffff8818cc4b in aster_nix::__ostd_main () at src/lib.rs:82
#46 0xffffffff882a3f36 in ostd::boot::call_ostd_main () at src/boot/mod.rs:127
#47 0xffffffff88282c4a in ostd::arch::x86::boot::multiboot2::__multiboot2_entry (boot_magic=920085129, boot_params=462848) at src/arch/x86/boot/multiboot2/mod.rs:177
#48 0xffffffff88295942 in entry_type_multiboot2 ()
#49 0x66d88e660000b866 in ?? ()
#50 0xe08e66c08e66d08e in ?? ()
#51 0x0000c3c748e88e66 in ?? ()
#52 0x048d48dc09488000 in ?? ()
#53 0xd80948082958e425 in ?? ()
#54 0xd88ec031fcfae0ff in ?? ()
#55 0xc0200f804016010f in ?? ()
#56 0xeac0220f01c88366 in ?? ()
#57 0x0000b48d0008804c in ?? ()
#58 0x0000000000009066 in ?? ()
#59 0x9a000000ffff0000 in ?? ()
#60 0x92000000ffff00cf in ?? ()
#61 0xb48d0000b48d00cf in ?? ()
#62 0x0000802000170000 in ?? ()
#63 0xb866906600000000 in ?? ()
#64 0xd08e66d88e660010 in ?? ()
#65 0x25320f0000001bb9 in ?? ()
#66 0x0004003d00000400 in ?? ()
#67 0xfee00020a10a7400 in ?? ()
#68 0x0802b909eb18e8c1 in ?? ()
#69 0xc78900eb320f0000 in ?? ()
#70 0x0f080013a015010f in ?? ()
```

**Comment by junyang-zh** [comment]
@sdww0 How about allocation-free logging?

**Comment by sdww0** [comment]
> @sdww0 How about allocation-free logging?

I think it is reasonable :)

**Comment by junyang-zh** [comment]
@sdww0 Could you provide a fix for us? Thanks very much in advance.

**Comment by sdww0** [comment]
> @sdww0 Could you provide a fix for us? Thanks very much in advance.

Ok, I will do it.
