### ISSUE TITLE
Nginx benchmark failed in latest commit

### ISSUE THREAD

**Issue by sdww0** [asterinas/asterinas#1406]
### Describe the bug

The nginx benchmark I tested before failed in the latest commit.

### To Reproduce

1. Change `NGINX_RAND_PORT` in `tools/qemu_args.sh` to 8080 
2. Run `cp /etc/nginx.conf /usr/local/nginx/conf/` and `/usr/local/nginx/sbin/nginx` in Asterinas (Release mode). 
3. In another shell, run `ab -n 10000 -c 1 http://localhost:8080/index.html`
5. Asterinas will panic with message: 
``` text
panicked at /home/waoa/dev-asterinas/ostd/src/task/atomic_mode.rs:41:9:
This function might break atomic mode (preempt_count = 3, is_local_irq_enabled = false)
```
OR the apache bench will output: `The timeout specified has expired (70007)`.

### Screenshots

Screenshot of the call stack:

![image](https://github.com/user-attachments/assets/fea0e869-b832-4ac9-865d-ba9347fcffb5)

### Additional context

I tested the benchmark in the historical commit and found that the problem seemed to arise after the commit: [ee1656ba35](https://github.com/asterinas/asterinas/commit/ee1656ba350871e36a79c83dd2fc9344083c56e7)

The cause of panic in Asterinas seems related to lock mutex in interrupt context.

**Comment by lrh2000** [comment]
OK, there are a total of six bugs causing this problem, but none of them are related to my latest commit https://github.com/asterinas/asterinas/commit/ee1656ba350871e36a79c83dd2fc9344083c56e7 mentioned above.

#### Bug 1: Dead lock: A chicken-egg problem between the heap allocator and page allocator

Backtrace:
```
#0  0xffffffff882a8772 in <ostd::mm::heap_allocator::LockedHeapWithRescue as core::alloc::global::GlobalAlloc>::alloc ()
#1  0xffffffff882da75d in alloc::collections::btree::map::BTreeMap<K,V,A>::insert ()
#2  0xffffffff882a67bf in buddy_system_allocator::frame::FrameAllocator<_>::alloc ()
#3  0xffffffff882a8972 in <ostd::mm::heap_allocator::LockedHeapWithRescue as core::alloc::global::GlobalAlloc>::alloc ()
#4  0xffffffff8804d6da in aster_bigtcp::socket::unbound::UnboundSocket<smoltcp::socket::tcp::Socket>::new ()
#5  0xffffffff88226243 in aster_nix::net::socket::ip::stream::listen::BacklogSocket::new ()
#6  0xffffffff88225c17 in aster_nix::net::socket::ip::stream::init::InitStream::listen ()
#7  0xffffffff880a58d6 in <aster_nix::net::socket::ip::stream::StreamSocket as aster_nix::net::socket::Socket>::listen ()
#8  0xffffffff880b2cf3 in aster_nix::syscall::listen::sys_listen ()
#9  0xffffffff880bc392 in aster_nix::syscall::arch::x86::syscall_dispatch ()
#10 0xffffffff880e1f2e in aster_nix::syscall::handle_syscall ()
#11 0xffffffff881fbb8b in aster_nix::thread::task::create_new_user_task::user_task_entry ()
#12 0xffffffff882b3794 in ostd::task::TaskOptions::build::kernel_task_entry ()
#13 0x0000000000000000 in ?? ()
```

This problem is originally reported in https://github.com/asterinas/asterinas/issues/1085#issuecomment-2249361926.

#### Bug 2: Atomic mode break: Locking `EpollFile::ready` mutex in interrupt handlers

This lock can be held in interrupt handlers, but it's a mutex.

https://github.com/asterinas/asterinas/blob/7d5a2b7a796da788cce43657c91c0f77dbc3195c/kernel/src/fs/epoll/epoll_file.rs#L33-L34

#### Bug 3: Dead lock: Missing `irq_disabled` when acquiring various `StreamSocket`-related locks

This method can be called in interrupt handlers, but the associated locks are never protected by disabling IRQ guards.

https://github.com/asterinas/asterinas/blob/7d5a2b7a796da788cce43657c91c0f77dbc3195c/kernel/src/net/socket/ip/stream/mod.rs#L639-L649

#### Bug 4: Busy loop: Race conditions in `LineDiscipline` when dealing with I/O events

The I/O event updates here cause race conditions because they are added later without holding the `read_buffer` lock:
https://github.com/asterinas/asterinas/blob/7d5a2b7a796da788cce43657c91c0f77dbc3195c/kernel/src/device/tty/line_discipline.rs#L193-L204

This causes wrong I/O events to be added, resulting in a busy loop `LineDiscipline::try_read`. Since we do not support kernel preemption, network events can never be processed.

#### Bug 5: Dead lock: Missing `irq_disabled` when acquiring locks in `Pollee`/`Subject`

I/O events may be added or removed in interrupt handlers, but the corresponding lock in `Subject` is not protected by disabling IRQ guards.
https://github.com/asterinas/asterinas/blob/7d5a2b7a796da788cce43657c91c0f77dbc3195c/kernel/src/events/subject.rs#L12-L13

#### Bug 6: Feature missing: Support `HUP`/`RDHUP`/`ERR` for TCP sockets

We currently have no support for `HUP`/`RDHUP`/`ERR` for TCP sockets:
https://github.com/asterinas/asterinas/blob/7d5a2b7a796da788cce43657c91c0f77dbc3195c/kernel/src/net/socket/ip/stream/connected.rs#L119-L133

This seems to cause Nginx to not properly close sockets that have already been closed by the remote side. However, the port may be reused later, causing a hang for ~10 seconds (time 68 -> time 86):

![image](https://github.com/user-attachments/assets/b5a66b7e-b147-4a31-8c23-824e0c2523e2)

**Comment by lrh2000** [comment]
All bugs have been fixed.
