### ISSUE TITLE
[BUG] Uncaught panic happened in heap_allocator

### ISSUE THREAD

**Issue by skpupil** [asterinas/asterinas#666]
I run 416.gamess , one of spec CPU 2006 test items,  but a pacnic happened:

```
~ # ./gamess_base.amd64-m64-gcc41-nn < exam29.config 
[ERROR]: Uncaught panic!
panicked at framework/aster-frame/src/vm/heap_allocator.rs:24:5:
Heap allocation error, layout = Layout { size: 659468632, align: 1 (1 << 0) }
```
This pacnic alse happened when I run 434.zeusmp.
the file of 434.zeusmp and 416.gamess: [https://github.com/skpupil/my_spec_test](url)

**Comment by junyang-zh** [comment]
We currently have only the ability to manage <4G of memory. And the default QEMU boot option gives a 2G memory. Maybe an allocation of 629MiB caused an OOM.

Related to #318

**Comment by junyang-zh** [comment]
```rust
    if segment_vmo_size > tail_padding_offset {
        let buffer = vec![0u8; segment_vmo_size - tail_padding_offset];
        segment_vmo.write_bytes(tail_padding_offset, &buffer)?;
    }
```

The troublemaker is found: the memsize of that segment is 629MiB. And we should do lazy zero out init rather than doing such a scary memset operation of vmo.

```
(gdb) bt
#0  alloc::alloc::handle_alloc_error (layout=...) at src/alloc.rs:389
#1  0xffffffff8904ba9e in alloc::raw_vec::RawVec<u8, alloc::alloc::Global>::allocate_in<u8, alloc::alloc::Global> (
    capacity=659468632, init=alloc::raw_vec::AllocInit::Zeroed, alloc=...) at src/raw_vec.rs:204
#2  0xffffffff88ed31e8 in alloc::raw_vec::RawVec<u8, alloc::alloc::Global>::with_capacity_zeroed_in<u8, alloc::alloc::Global> (capacity=659468632, alloc=...)
    at /root/.rustup/toolchains/nightly-2024-01-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:153
#3  0xffffffff88ece3f4 in alloc::vec::spec_from_elem::{impl#3}::from_elem<alloc::alloc::Global> (elem=0, n=659468632, 
    alloc=...)
    at /root/.rustup/toolchains/nightly-2024-01-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_elem.rs:52
#4  0xffffffff88ed190f in alloc::vec::from_elem<u8> (elem=0, n=659468632)
    at /root/.rustup/toolchains/nightly-2024-01-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2627
#5  0xffffffff88b11985 in aster_nix::process::program_loader::elf::load_elf::init_segment_vmo (
    program_header=0xffff80000c8d2d18, elf_file=0xffff80000c184810) at src/process/program_loader/elf/load_elf.rs:309
#6  0xffffffff88b103cd in aster_nix::process::program_loader::elf::load_elf::map_segment_vmos (elf=0xffff800003dbd6d8, 
    root_vmar=0xffff80000c8df010, elf_file=0xffff80000c184810) at src/process/program_loader/elf/load_elf.rs:201
#7  0xffffffff88b0faa0 in aster_nix::process::program_loader::elf::load_elf::init_and_map_vmos (
    process_vm=0xffff80000c8df010, ldso=..., elf=0xffff800003dbd6d8, elf_file=0xffff80000c184810, argv=..., envp=..., 
    vdso_text_base=1064960) at src/process/program_loader/elf/load_elf.rs:123
#8  0xffffffff88b0eece in aster_nix::process::program_loader::elf::load_elf::load_elf_to_vm (
    process_vm=0xffff80000c8df010, file_header=..., elf_file=..., fs_resolver=0xffff80000c8cf910, argv=..., envp=..., 
    vdso_text_base=1064960) at src/process/program_loader/elf/load_elf.rs:55
#9  0xffffffff88b0e212 in aster_nix::process::program_loader::load_program_to_vm (process_vm=0xffff80000c8df010, 
    elf_file=..., argv=..., envp=..., fs_resolver=0xffff80000c8cf910, recursion_limit=1)
    at src/process/program_loader/mod.rs:89
#10 0xffffffff88d11dc3 in aster_nix::syscall::execve::do_execve (elf_file=..., argv_ptr_ptr=268442568, 
    envp_ptr_ptr=268442632, context=0xffff800003dc09c0) at src/syscall/execve.rs:119
#11 0xffffffff88d107b7 in aster_nix::syscall::execve::sys_execve (filename_ptr=268442504, argv_ptr_ptr=268442568, 
    envp_ptr_ptr=268442632, context=0xffff800003dc09c0) at src/syscall/execve.rs:36
#12 0xffffffff88d0cd6e in aster_nix::syscall::syscall_dispatch (syscall_number=59, args=..., context=0xffff800003dc09c0)
    at src/syscall/mod.rs:462
#13 0xffffffff88d0c4dc in aster_nix::syscall::handle_syscall (context=0xffff800003dc09c0) at src/syscall/mod.rs:397
#14 0xffffffff88d09fee in aster_nix::thread::task::handle_user_event (user_event=aster_frame::user::UserEvent::Syscall, 
    context=0xffff800003dc09c0) at src/thread/task.rs:71
#15 0xffffffff88d09a6d in aster_nix::thread::task::create_new_user_task::user_task_entry () at src/thread/task.rs:37
#16 0xffffffff88d3f8ce in core::ops::function::Fn::call<fn(), ()> ()
    at /root/.rustup/toolchains/nightly-2024-01-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
#17 0xffffffff88fc6ad6 in alloc::boxed::{impl#49}::call<(), (dyn core::ops::function::Fn<(), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global> (self=0xffff80000c8cfe40, args=()) at /root/.rustup/toolchains/nightly-2024-01-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029
#18 0xffffffff88fac554 in aster_frame::task::task::{impl#3}::build::kernel_task_entry () at src/task/task.rs:259
(gdb) f 6
#6  0xffffffff88b103cd in aster_nix::process::program_loader::elf::load_elf::map_segment_vmos (elf=0xffff800003dbd6d8, 
    root_vmar=0xffff80000c8df010, elf_file=0xffff80000c184810) at src/process/program_loader/elf/load_elf.rs:201
201                 let vmo = init_segment_vmo(program_header, elf_file)?;
(gdb) p *program_header
$3 = xmas_elf::program::ProgramHeader64 {type_: xmas_elf::program::Type_ (1), flags: xmas_elf::program::Flags (6), offset: 8596504, virtual_addr: 8600600, physical_addr: 8600600, file_size: 66192, mem_size: 659531104, align: 4096}
```
