### ISSUE TITLE
"[ERROR]: Uncaught panic!" when running the 100-line kernel example in the asterinas book.

### ISSUE THREAD

**Issue by dxy-cs** [asterinas/asterinas#871]
When running the 100-line kernel example in the asterinas book [https://asterinas.github.io/book/framework/a-100-line-kernel.html ](url), the following error is reported:
```
Drive current: -outdev 'stdio:/root/workspace/asterinas/target/osdk/myos-osdk-bin.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data,  931g free
Added to ISO image: directory '/'='/tmp/grub.CQmOUp'
xorriso : UPDATE :     341 files added in 1 seconds
Added to ISO image: directory '/'='/root/workspace/asterinas/target/osdk/iso_root'
xorriso : UPDATE :     346 files added in 1 seconds
xorriso : UPDATE :  0.00% done
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0)
WARNING: no console will be available to OS
error: no suitable video mode found.
[ERROR]: Uncaught panic!
panicked at /root/workspace/asterinas/framework/aster-frame/src/task/scheduler.rs:44:24:
called `Option::unwrap()` on a `None` value
printing stack trace:
   1: fn 0xffffffff8809f660 - pc 0xffffffff8809f678 / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047820;

   2: fn 0xffffffff8809f160 - pc 0xffffffff8809f617 / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047830;

   3: fn 0xffffffff88048030 - pc 0xffffffff8804803a / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047a80;

   4: fn 0xffffffff8818f4a0 - pc 0xffffffff8818f4ef / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047a90;

   5: fn 0xffffffff8818f5d0 - pc 0xffffffff8818f615 / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047ae0;

   6: fn 0xffffffff88124fd0 - pc 0xffffffff88125011 / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047b50;

   7: fn 0xffffffff8806efa0 - pc 0xffffffff8806efce / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047b80;

   8: fn 0xffffffff8806f0c0 - pc 0xffffffff8806f16e / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047bc0;

   9: fn 0xffffffff8806e450 - pc 0xffffffff8806e462 / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047c20;

  10: fn 0xffffffff880489e0 - pc 0xffffffff88048a30 / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047c30;

  11: fn 0xffffffff880489d0 - pc 0xffffffff880489db / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047f50;

  12: fn 0xffffffff880a3b00 - pc 0xffffffff880a3b06 / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047f60;

  13: fn 0xffffffff8810d3b0 - pc 0xffffffff8810d477 / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88047f70;

  14: fn                0x0 - pc 0xffffffff880ad052 / registers:

     rax                0x1; rdx 0xffffffff881a43f0; rcx               0x16; rbx 0xffffffff80000000;
     rsi 0xffffffff881a4358; rdi 0xffffffff880479e8; rbp                0x0; rsp 0xffffffff88048000;
```

**Comment by junyang-zh** [comment]
It seems that the scheduler is not set. And the guide does not mention that.

```rust
use aster_frame::task::{set_scheduler, FifoScheduler, Scheduler};
let simple_scheduler = Box::new(FifoScheduler::new());
let static_scheduler: &'static dyn Scheduler = Box::leak(simple_scheduler);
set_scheduler(static_scheduler);
```

Could you please check if this works? If so you can help us improve the guide!

**Comment by dxy-cs** [comment]
Thanks. After adding your code into the example, the program runs successfully and outputs "Hello, world". However, the below error message follows. Is this normal? 
```
WARNING: no console will be available to OS
error: no suitable video mode found.
Hello, world

[ERROR]: Uncaught panic!
panicked at /root/workspace/asterinas/framework/aster-frame/src/task/task.rs:191:9:
internal error: entered unreachable code
printing stack trace:
   1: fn 0xffffffff880a1840 - pc 0xffffffff880a1858 / registers:

     rax                0x1; rdx 0xffffffff881a6db0; rcx               0x16; rbx                0x0;
     rsi 0xffffffff881a6d18; rdi 0xffff8000083c0898; rbp                0x0; rsp 0xffff8000083c06d0;

   2: fn 0xffffffff880a1340 - pc 0xffffffff880a17f7 / registers:

     rax                0x1; rdx 0xffffffff881a6db0; rcx               0x16; rbx                0x0;
     rsi 0xffffffff881a6d18; rdi 0xffff8000083c0898; rbp                0x0; rsp 0xffff8000083c06e0;

   3: fn 0xffffffff88048030 - pc 0xffffffff8804803a / registers:

     rax                0x1; rdx 0xffffffff881a6db0; rcx               0x16; rbx                0x0;
     rsi 0xffffffff881a6d18; rdi 0xffff8000083c0898; rbp                0x0; rsp 0xffff8000083c0930;

   4: fn 0xffffffff88191e30 - pc 0xffffffff88191e7f / registers:

     rax                0x1; rdx 0xffffffff881a6db0; rcx               0x16; rbx                0x0;
     rsi 0xffffffff881a6d18; rdi 0xffff8000083c0898; rbp                0x0; rsp 0xffff8000083c0940;

   5: fn 0xffffffff88191f60 - pc 0xffffffff88191fa5 / registers:

     rax                0x1; rdx 0xffffffff881a6db0; rcx               0x16; rbx                0x0;
     rsi 0xffffffff881a6d18; rdi 0xffff8000083c0898; rbp                0x0; rsp 0xffff8000083c0990;

   6: fn 0xffffffff8806ee80 - pc 0xffffffff8806eef9 / registers:

     rax                0x1; rdx 0xffffffff881a6db0; rcx               0x16; rbx                0x0;
     rsi 0xffffffff881a6d18; rdi 0xffff8000083c0898; rbp                0x0; rsp 0xffff8000083c0a00;

   7: fn 0xffffffff88048660 - pc 0xffffffff880489c7 / registers:

     rax                0x1; rdx 0xffffffff881a6db0; rcx               0x16; rbx                0x0;
     rsi 0xffffffff881a6d18; rdi 0xffff8000083c0898; rbp                0x0; rsp 0xffff8000083c0a40;

   8: fn 0xffffffff880484d0 - pc 0xffffffff8804863c / registers:

     rax                0x1; rdx 0xffffffff881a6db0; rcx               0x16; rbx                0x0;
     rsi 0xffffffff881a6d18; rdi 0xffff8000083c0898; rbp                0x0; rsp 0xffff8000083c0c10;

   9: fn 0xffffffff88049e60 - pc 0xffffffff88049e6e / registers:

     rax                0x1; rdx 0xffffffff881a6db0; rcx               0x16; rbx                0x0;
     rsi 0xffffffff881a6d18; rdi 0xffff8000083c0898; rbp                0x0; rsp 0xffff8000083c0f90;

  10: fn 0xffffffff880bae20 - pc 0xffffffff880bae36 / registers:

     rax                0x1; rdx 0xffffffff881a6db0; rcx               0x16; rbx                0x0;
     rsi 0xffffffff881a6d18; rdi 0xffff8000083c0898; rbp                0x0; rsp 0xffff8000083c0fb0;

  11: fn 0xffffffff8806f710 - pc 0xffffffff8806f774 / registers:

     rax                0x1; rdx 0xffffffff881a6db0; rcx               0x16; rbx                0x0;
     rsi 0xffffffff881a6d18; rdi 0xffff8000083c0898; rbp                0x0; rsp 0xffff8000083c0fd0;
```

**Comment by junyang-zh** [comment]
Yes it is normal and the scheduler expect that the main task of the kernel will never return.

So a well formed hello world kernel may shut the system down after printing.

However we do not have ACPI shutdown at this moment. Here is a debug fix.

```rust
#[aster_main]
pub fn main() {
    let program_binary = include_bytes!("../hello_world");
    let user_space = create_user_space(program_binary);
    let user_task = create_user_task(Arc::new(user_space));
    user_task.run();
    use aster_frame::arch::qemu::{exit_qemu, QemuExitCode};
    exit_qemu(QemuExitCode::Success);
}
```

**Comment by dxy-cs** [comment]
Ok! Thanks again.

**Comment by grief8** [comment]
> It seems that the scheduler is not set. And the guide does not mention that.
> 
> ```rust
> use aster_frame::task::{set_scheduler, FifoScheduler, Scheduler};
> let simple_scheduler = Box::new(FifoScheduler::new());
> let static_scheduler: &'static dyn Scheduler = Box::leak(simple_scheduler);
> set_scheduler(static_scheduler);
> ```
> 
> Could you please check if this works? If so you can help us improve the guide!

#748 introduces such a scheduler initialization for `ktest`. Maybe it will be better to set the scheduler in `aster_frame::init()` and it will work for both.
